### ISSUE TITLE
Make it more apparent when your site will be deleted

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/TryOrchardCore#4]
I can't find any info on when your site is deleted. This should be apparent right there on the homepage when you create the site, and possibly also in the site creation e-mail.

@agriffard it's like every week or something, right? I can't find the mechanism for this in the code. I'm adding this to the OC docs too.

**Comment by agriffard** [comment]
There used to be a notice.

I disable manually the sites created during the week, every Sunday evening.

**Comment by Piedone** [comment]
I see, thanks.

**Comment by agriffard** [comment]
I added a mention in the email in order to warn that the site will be disabled the next Sunday.

**Comment by Piedone** [comment]
Great, thanks!
